In [1]:
import numpy as np

In [2]:
from sklearn .datasets import load_diabetes

In [3]:
from sklearn .linear_model import LinearRegression

In [4]:
from sklearn .metrics import r2_score

In [5]:
from sklearn .model_selection import train_test_split

In [6]:
x,y = load_diabetes(return_X_y=True)

In [7]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [9]:
reg =LinearRegression()

In [10]:
reg.fit(x_train,y_train)

LinearRegression()

In [11]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [12]:
reg.intercept_

151.88331005254167

In [13]:
y_pred =reg.predict(x_test)
r2_score(y_test,y_pred)

0.4399338661568969

In [14]:
import random
class MBGDRegressor:
    def __init__(self,batch_size,learning_rate=0.01,epochs=100):
        self.coef_ = None
        self.intercept_= None
        self.lr = learning_rate
        self.epochs =epochs
        self.batch_size = batch_size
    def fit(self,x_train,y_train):
        # init your coefs
        self.intercept_= 0
        self.coef_ = np.ones(x_train.shape[1])   
        for i in range(self.epochs):
            for j in range(int(x_train.shape[0]/self.batch_size)):
                idx = random.sample(range(x_train[0]),self.batch_size)
            #update all the coef and the  intercept
                y_hat = np.dot(x_train[idx],self.coef_)+ self.intercept_
           # print("shape of y_hat",y_hat.shape)
                intercept_der = -2*np.mean(y_train[idx]-  y_hat)
                self.intercept_ = self.intercept_-(self.lr * intercept_der)
                coef_der = -2 * np.dot((y_train[idx] - y_hat),x_train[idx])
                self.coef_ = self.coef_-(self.lr * coef_der)
        print(self.intercept_,self.coef_) 
    def predict(self,x_test):
        return np.dot(x_test,self.coef_) + self.intercept_           

In [15]:
mbr = MBGDRegressor(batch_size=int(x_train.shape[0]/10),learning_rate=0.01,epochs=50)

In [16]:
import random
random.sample(range(1,100),10)

[16, 48, 67, 23, 82, 94, 71, 7, 15, 64]

In [17]:
x_train

array([[-0.00188202, -0.04464164, -0.06979687, ..., -0.03949338,
        -0.06291688,  0.04034337],
       [-0.00914709, -0.04464164,  0.01103904, ..., -0.03949338,
         0.01703607, -0.0052198 ],
       [ 0.02354575,  0.05068012, -0.02021751, ..., -0.03949338,
        -0.09643495, -0.01764613],
       ...,
       [ 0.06350368,  0.05068012, -0.00405033, ..., -0.00259226,
         0.08449153, -0.01764613],
       [-0.05273755,  0.05068012, -0.01806189, ...,  0.1081111 ,
         0.03606033, -0.04249877],
       [ 0.00175052,  0.05068012,  0.05954058, ...,  0.1081111 ,
         0.06898589,  0.12732762]])

In [42]:
y_train

array([ 48., 276.,  47., 175.,  60.,  81., 242., 197., 137., 129., 138.,
       160., 116., 101., 147., 100., 144.,  69., 219., 107., 168., 236.,
       109., 321., 128.,  43.,  72.,  55., 141., 283.,  59., 150., 346.,
       124., 186., 308., 272., 190.,  63.,  91.,  72.,  65., 158.,  90.,
       185.,  45., 199., 206.,  61., 139., 296., 281., 122.,  95.,  40.,
       127., 145., 108., 185.,  53., 132., 101., 263.,  94., 295., 259.,
       232., 124.,  77., 102.,  96.,  83., 263.,  71., 246.,  66., 115.,
       222.,  93., 129., 128., 163.,  99.,  92., 179., 140.,  94.,  97.,
       174.,  61., 202., 135.,  88., 152.,  69.,  31., 248., 275.,  64.,
        94.,  99., 109.,  90.,  37., 164., 274., 200.,  49., 214.,  85.,
       154., 134., 164., 189.,  64., 150., 245.,  67., 265., 151.,  75.,
       208., 292.,  90.,  59.,  44., 277.,  67.,  72., 182., 135., 275.,
        95., 332., 214.,  53., 141., 102.,  88.,  74., 103., 292.,  70.,
       138., 139.,  98.,  72.,  25.,  72., 264.,  9