In [25]:
import numpy as np

In [26]:
from sklearn .datasets import load_diabetes

In [27]:
from sklearn .linear_model import LinearRegression

In [28]:
from sklearn .metrics import r2_score

In [29]:
from sklearn .model_selection import train_test_split

In [62]:
x,y = load_diabetes(return_X_y=True)

In [31]:
x.shape

(442, 10)

In [32]:
y.shape

(442,)

In [33]:
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [34]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [63]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [64]:
x_train

array([[-0.00188202, -0.04464164, -0.06979687, ..., -0.03949338,
        -0.06291688,  0.04034337],
       [-0.00914709, -0.04464164,  0.01103904, ..., -0.03949338,
         0.01703607, -0.0052198 ],
       [ 0.02354575,  0.05068012, -0.02021751, ..., -0.03949338,
        -0.09643495, -0.01764613],
       ...,
       [ 0.06350368,  0.05068012, -0.00405033, ..., -0.00259226,
         0.08449153, -0.01764613],
       [-0.05273755,  0.05068012, -0.01806189, ...,  0.1081111 ,
         0.03606033, -0.04249877],
       [ 0.00175052,  0.05068012,  0.05954058, ...,  0.1081111 ,
         0.06898589,  0.12732762]])

In [65]:
y_train

array([ 48., 276.,  47., 175.,  60.,  81., 242., 197., 137., 129., 138.,
       160., 116., 101., 147., 100., 144.,  69., 219., 107., 168., 236.,
       109., 321., 128.,  43.,  72.,  55., 141., 283.,  59., 150., 346.,
       124., 186., 308., 272., 190.,  63.,  91.,  72.,  65., 158.,  90.,
       185.,  45., 199., 206.,  61., 139., 296., 281., 122.,  95.,  40.,
       127., 145., 108., 185.,  53., 132., 101., 263.,  94., 295., 259.,
       232., 124.,  77., 102.,  96.,  83., 263.,  71., 246.,  66., 115.,
       222.,  93., 129., 128., 163.,  99.,  92., 179., 140.,  94.,  97.,
       174.,  61., 202., 135.,  88., 152.,  69.,  31., 248., 275.,  64.,
        94.,  99., 109.,  90.,  37., 164., 274., 200.,  49., 214.,  85.,
       154., 134., 164., 189.,  64., 150., 245.,  67., 265., 151.,  75.,
       208., 292.,  90.,  59.,  44., 277.,  67.,  72., 182., 135., 275.,
        95., 332., 214.,  53., 141., 102.,  88.,  74., 103., 292.,  70.,
       138., 139.,  98.,  72.,  25.,  72., 264.,  9

In [66]:
reg =LinearRegression()

In [67]:
reg.fit(x_train,y_train)

LinearRegression()

In [68]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [69]:
reg.intercept_

151.88331005254167

In [70]:
y_pred =reg.predict(x_test)
r2_score(y_test,y_pred)

0.4399338661568969

In [71]:
class SGDRegressor:
    def __init__(self,learning_rate=0.01,epochs=100):
        self.coef_ = None
        self.intercept_= None
        self.lr = learning_rate
        self.epochs =epochs
    def fit(self,x_train,y_train):
        # init your coefs
        self.intercept_= 0
        self.coef_ = np.ones(x_train.shape[1])   
        
        for i in range(self.epochs):
            for j in range(x_train.shape[0]):
                idx = np.random.randint(0,x_train.shape[0])
                y_hat = np.dot(x_train[idx],self.coef_)+ self.intercept_
                #intercept _der
                intercept_der = -2 *(y_train[idx]-  y_hat)
                self.intercept_ = self.intercept_-(self.lr * intercept_der)
                #coef_
                coef_der = -2 *np.dot ((y_train[idx] - y_hat),x_train[idx])
                self.coef_ = self.coef_-(self.lr * coef_der)

        print(self.intercept_,self.coef_)
def predict(self,x_test):
        return np.dot(x_test,self.coef_) + self.intercept_     

In [16]:
np.random.randint(0,x_train.shape[0])

245

In [17]:
x_train[245]

array([-0.06000263,  0.05068012,  0.01535029, -0.01944183,  0.03695772,
        0.04816358,  0.019187  , -0.00259226, -0.03074792, -0.0010777 ])

In [19]:
coef_ = np.ones(x_train.shape[1])

In [20]:
intercept_ = 0

In [21]:
np.dot(x_train[245],coef_)+ intercept_

0.05647636787302532

In [72]:
sgd = SGDRegressor(learning_rate=0.01,epochs=50)

In [73]:
sgd.fit(x_train,y_train)

159.52201636040144 [  53.35250865  -62.847279    363.56843269  241.6380354     8.14424552
  -34.682691   -179.69809329  131.41925975  320.07659384  131.37819636]
